# -*- coding: utf-8 -*-
"""stutter_correction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ye_mi1H5BoIAeK-odXcDkkXhB1VAqFgn
"""

pip install transformers torchaudio indic_transliteration edge_tts asyncio

"""AUDIO UPLOAD"""

from google.colab import files
u=files.upload()

"""PREPROCESSING AUDIO"""

import torchaudio
import torchaudio.transforms as T

waveform,sr=torchaudio.load("M11_C1_S2.wav")

if waveform.shape[0]>1:
    waveform=waveform.mean(dim=0)
else:
  waveform=waveform.squeeze()

target_rate=16000
if sr!=target_rate:
    resample=T.Resample(sr,target_rate)
    waveform=resample(waveform)
    sr=target_rate

waveform=waveform/waveform.abs().max()
print(waveform.shape)

from IPython.display import Audio

Audio(waveform,rate=sr)

"""TRANSCRIPTION"""

from transformers import WhisperProcessor,WhisperForConditionalGeneration
import torch

processor=WhisperProcessor.from_pretrained("openai/whisper-small")
model=WhisperForConditionalGeneration.from_pretrained("openai/whisper-small")

chunks=[]
step_size=30*sr
overlap_len=5*sr

device="cuda" if torch.cuda.is_available() else "cpu"
model=model.to(device)

for i in range(0,waveform.shape[0],step_size-overlap_len):
    chunk=waveform[i:i+step_size]
    chunks.append(chunk)

text=""
for chunk in chunks:
    inputs=processor(chunk,sampling_rate=16000,return_tensors="pt",return_attention_mask=True)
    input_features=inputs["input_features"].to(device)

    with torch.no_grad():
      predicted_ids=model.generate(input_features,forced_decoder_ids=processor.get_decoder_prompt_ids(language="hi",task="transcribe"),no_repeat_ngram_size=3,repetition_penalty=1.2)


    transcription=processor.batch_decode(predicted_ids,skip_special_tokens=True)[0]

    text+=transcription


print(text)

"""TRANSLITERATION"""

from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate

transcription = transliterate(text, sanscript.DEVANAGARI, sanscript.ITRANS)

print(transcription)

from google.colab import files
x=files.upload()

"""LLM INTEGRATION"""

from google import genai
import os
from dotenv import load_dotenv

load_dotenv(".env")
api_key=os.getenv("GEMINI_API_KEY")
client=genai.Client(api_key=api_key)

prompt=f'''

You are a stutter corrector,the text which i give you is in
transliterated hindi,but it is has disfluencies present.

Your task is to:
-give me text which makes full sense and can be understood
-text should be in transliterated hindi
-it should not have any filler words or unneccesary repetitions
-dont add any extra information
-preserve orignal context
-if context not clear,try to make the best understanding of the context and give clear output

{transcription}'''


response=client.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt
)
print(response.text)

"""TEXT-TO-SPEECH(TTS)"""

import edge_tts
import asyncio

async def main():
  tts=edge_tts.Communicate(response.text,"en-IN-PrabhatNeural")

  await tts.save("output.mp3")

await main()

from google.colab import files
files.download("output.mp3")